#!/usr/bin/env python3
"""
generate-seo.py — SEO file generator for QNFO/QWAV publications.
Generates sitemap.xml, robots.txt, and llms.txt for discoverability.
v1.0 — 2026-05-31

Usage:
  python generate-seo.py --domain deep.qwav.tech --dir "G:/My Drive/QWAV" --base-url "https://deep.qwav.tech"
  python generate-seo.py --domain laws.qnfo.org --dir "G:\My Drive\projects\qlof\deploy"
"""

import argparse
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urljoin, quote
from xml.etree.ElementTree import Element, SubElement, tostring
from xml.dom import minidom


def discover_html_files(root_dir):
    """Recursively find all .html files in a directory tree."""
    html_files = []
    root = Path(root_dir)
    for f in root.rglob('*.html'):
        # Skip node_modules, .git, _site, etc.
        if any(part.startswith('.') or part.startswith('_') or part == 'node_modules'
               for part in f.parts):
            continue
        html_files.append(f)
    return sorted(html_files)


def get_lastmod(filepath):
    """Get ISO 8601 last-modified date for a file."""
    mtime = os.path.getmtime(filepath)
    dt = datetime.fromtimestamp(mtime, tz=timezone.utc)
    return dt.strftime('%Y-%m-%d')


def url_from_path(filepath, root_dir, base_url):
    """Convert filesystem path to URL path."""
    rel_path = Path(filepath).relative_to(root_dir)
    # index.html -> directory URL
    if rel_path.name == 'index.html':
        url_path = str(rel_path.parent).replace('\\', '/')
        if url_path == '.':
            url_path = ''
    else:
        url_path = str(rel_path).replace('\\', '/')
    return urljoin(base_url.rstrip('/') + '/', url_path)


def generate_sitemap(html_files, root_dir, base_url):
    """Generate sitemap.xml."""
    urlset = Element('urlset', {
        'xmlns': 'http://www.sitemaps.org/schemas/sitemap/0.9',
        'xmlns:xhtml': 'http://www.w3.org/1999/xhtml',
    })
    
    for filepath in html_files:
        url_elem = SubElement(urlset, 'url')
        
        loc = SubElement(url_elem, 'loc')
        loc.text = url_from_path(filepath, root_dir, base_url)
        
        lastmod = SubElement(url_elem, 'lastmod')
        lastmod.text = get_lastmod(filepath)
        
        # Priority: root > section > leaf
        rel = Path(filepath).relative_to(root_dir)
        depth = len(rel.parts)
        if depth <= 1:
            priority = '1.0'
        elif depth <= 2:
            priority = '0.8'
        else:
            priority = '0.5'
        prio = SubElement(url_elem, 'priority')
        prio.text = priority
    
    xml_str = minidom.parseString(tostring(urlset, 'utf-8')).toprettyxml(indent='  ')
    return '<?xml version="1.0" encoding="UTF-8"?>\n' + xml_str.split('\n', 1)[1]


def generate_robots_txt(base_url, sitemap_exists=True):
    """Generate robots.txt allowing all crawlers."""
    lines = [
        '# robots.txt — QNFO Research Infrastructure',
        '# Generated by generate-seo.py',
        '',
        'User-agent: *',
        'Allow: /',
        '',
    ]
    if sitemap_exists:
        lines.append(f'Sitemap: {base_url.rstrip("/")}/sitemap.xml')
    
    return '\n'.join(lines) + '\n'


def generate_llms_txt(html_files, root_dir, base_url, domain):
    """Generate llms.txt — AI-readable site index (llmstxt.org spec)."""
    lines = [
        f'# {domain}',
    ]
    
    # Try to find a description from the root index.html
    root_index = Path(root_dir) / 'index.html'
    description = ''
    if root_index.exists():
        import re
        text = root_index.read_text(encoding='utf-8', errors='replace')
        # Try meta description
        m = re.search(r'<meta\s+name="description"\s+content="([^"]+)"', text, re.IGNORECASE)
        if m:
            description = m.group(1)
        else:
            # Try first substantial paragraph
            m = re.search(r'<p[^>]*>(.{50,200})</p>', text)
            if m:
                import html
                description = html.unescape(re.sub(r'<[^>]+>', '', m.group(1))).strip()
    
    if description:
        lines.append(f'> {description}')
    lines.append('')
    
    for filepath in html_files:
        url = url_from_path(filepath, root_dir, base_url)
        rel = Path(filepath).relative_to(root_dir)
        
        # Extract title from HTML
        title = rel.stem.replace('-', ' ').title()
        try:
            text = filepath.read_text(encoding='utf-8', errors='replace')
            import re as re_mod
            m = re_mod.search(r'<title[^>]*>(.+?)</title>', text, re_mod.IGNORECASE)
            if m:
                import html
                title = html.unescape(m.group(1)).strip()
        except Exception:
            pass
        
        # Get a snippet
        snippet = ''
        try:
            text = filepath.read_text(encoding='utf-8', errors='replace')
            m = re.search(r'<p[^>]*>(.{40,150})</p>', text)
            if m:
                import html
                snippet = ' — ' + html.unescape(re.sub(r'<[^>]+>', '', m.group(1))).strip()
        except Exception:
            pass
        
        # Indent based on depth
        depth = max(0, len(rel.parts) - 1)
        indent = '  ' * depth
        
        is_index = rel.name == 'index.html'
        prefix = '- ' if not is_index else ''
        lines.append(f'{indent}{prefix}[{title}]({url}){snippet}')
    
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser(description="Generate SEO files for QNFO publications")
    parser.add_argument('--domain', required=True, help='Site domain (e.g., deep.qwav.tech)')
    parser.add_argument('--dir', required=True, help='Root directory containing HTML files')
    parser.add_argument('--base-url', help='Base URL (defaults to https://domain)')
    parser.add_argument('--no-sitemap', action='store_true', help='Skip sitemap.xml generation')
    parser.add_argument('--no-llms', action='store_true', help='Skip llms.txt generation')
    parser.add_argument('--dry-run', action='store_true', help='Print files that would be generated')
    args = parser.parse_args()
    
    root_dir = Path(args.dir)
    if not root_dir.exists():
        print(f"[ERROR] Directory not found: {args.dir}")
        sys.exit(1)
    
    base_url = args.base_url or f'https://{args.domain}'
    
    # Discover HTML files
    html_files = discover_html_files(root_dir)
    if not html_files:
        print(f"[WARN] No HTML files found in {args.dir}")
        return
    
    print(f"[OK] Found {len(html_files)} HTML files")
    
    output_files = {}
    
    # Generate sitemap.xml
    if not args.no_sitemap:
        sitemap_content = generate_sitemap(html_files, root_dir, base_url)
        output_files['sitemap.xml'] = sitemap_content
    
    # Generate robots.txt
    robots_content = generate_robots_txt(base_url, sitemap_exists=(not args.no_sitemap))
    output_files['robots.txt'] = robots_content
    
    # Generate llms.txt
    if not args.no_llms:
        llms_content = generate_llms_txt(html_files, root_dir, base_url, args.domain)
        output_files['llms.txt'] = llms_content
    
    if args.dry_run:
        print("\n[DRY RUN] Would generate:")
        for filename, content in output_files.items():
            output_path = root_dir / filename
            print(f"  {output_path} ({len(content)} bytes)")
    else:
        for filename, content in output_files.items():
            output_path = root_dir / filename
            output_path.write_text(content, encoding='utf-8')
            print(f"[OK] Generated: {output_path} ({len(content)} bytes)")


if __name__ == '__main__':
    main()
