/**
 * ipatent.me API Worker
 * US Provisional Disclosure Generator + Analytics
 *
 * Endpoints:
 *   POST /api/submit — Generate provisional disclosure
 *   POST /api/analytics — Record page view / event
 *   GET  /api/health — Health check
 *   GET  /api/stats — Aggregate analytics (admin)
 */

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
  'Access-Control-Max-Age': '86400',
};

function cors(response) {
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers: { ...Object.fromEntries(response.headers), ...CORS_HEADERS },
  });
}

function json(data, status = 200) {
  return cors(new Response(JSON.stringify(data, null, 2), {
    status,
    headers: { 'Content-Type': 'application/json' },
  }));
}

function generateSubmissionId() {
  const ts = Date.now().toString(36).toUpperCase();
  const rand = crypto.randomUUID().split('-')[0].toUpperCase();
  return `USP-${ts}-${rand}`;
}

function generateDisclosureHTML(data) {
  const now = new Date().toISOString().split('T')[0];
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>US Provisional Disclosure — ${data.title || 'Untitled Invention'}</title>
<style>
  body { font-family: 'Segoe UI', system-ui, sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; color: #1a1a2e; line-height: 1.7; }
  h1 { font-size: 1.5rem; border-bottom: 3px solid #4f46e5; padding-bottom: 10px; }
  h2 { font-size: 1.1rem; color: #4f46e5; margin-top: 24px; }
  .meta { background: #f3f4f6; padding: 16px; border-radius: 8px; margin: 16px 0; font-size: 0.9rem; }
  .disclosure { background: #fefefe; border: 1px solid #e5e7eb; padding: 24px; border-radius: 8px; margin: 16px 0; white-space: pre-wrap; }
  .footer { font-size: 0.75rem; color: #9ca3af; margin-top: 40px; border-top: 1px solid #e5e7eb; padding-top: 16px; }
  .watermark { position: fixed; top: 50%; left: 50%; transform: translate(-50%,-50%) rotate(-25deg); font-size: 6rem; color: rgba(79,70,229,0.03); pointer-events: none; z-index: -1; white-space: nowrap; }
  @media print { .watermark { display: none; } body { font-size: 11pt; } }
</style>
</head>
<body>
<div class="watermark">DRAFT</div>
<h1>UNITED STATES PROVISIONAL PATENT DISCLOSURE</h1>
<div class="meta">
  <p><strong>Submission ID:</strong> ${data.submission_id}</p>
  <p><strong>Date Generated:</strong> ${now}</p>
  <p><strong>Inventor:</strong> ${data.inventor_name || 'Not provided'}</p>
  <p><strong>Contact:</strong> ${data.inventor_email || 'Not provided'}</p>
  <p><strong>Status:</strong> DRAFT — Not yet filed with USPTO</p>
</div>
<h2>Title of Invention</h2>
<p>${data.title || '[Title not provided]'}</p>
<h2>Detailed Disclosure</h2>
<div class="disclosure">${data.disclosure_text || '[No detailed disclosure provided]'}</div>
<h2>Inventor Declaration</h2>
<p>I, <strong>${data.inventor_name || '[Name not provided]'}</strong>, hereby declare that I am the original inventor of the subject matter disclosed above. I understand this document is a <strong>draft disclosure only</strong> and does <em>not</em> constitute a filed provisional patent application with the United States Patent and Trademark Office (USPTO).</p>
<p>To obtain a filing date, this disclosure must be submitted to the USPTO as a provisional application with the required forms, drawings, and filing fee.</p>
<h2>Next Steps</h2>
<ol>
  <li>Review and refine this disclosure thoroughly</li>
  <li>Add any drawings, diagrams, or schematics</li>
  <li>File as a USPTO provisional application (Forms SB/16, specification, drawings, fee)</li>
  <li>Consult a registered patent attorney or agent</li>
</ol>
<div class="footer">
  <p>Generated by ipatent.me — US Provisional Disclosure Tool</p>
  <p>This is NOT a filed patent application. No USPTO filing date has been established.</p>
  <p>Generated: ${now} | Submission ID: ${data.submission_id}</p>
</div>
</body>
</html>`;
}

// ── Request Handlers ──

async function handleSubmit(request, env) {
  if (request.method !== 'POST') {
    return json({ error: 'Method not allowed. Use POST.' }, 405);
  }

  let body;
  try {
    body = await request.json();
  } catch {
    return json({ error: 'Invalid JSON body' }, 400);
  }

  const { inventor_name, inventor_email, title, disclosure_text } = body;

  if (!title || !disclosure_text) {
    return json({ error: 'title and disclosure_text are required' }, 400);
  }

  const submissionId = generateSubmissionId();
  const ip = request.headers.get('CF-Connecting-IP') || 'unknown';
  const ua = request.headers.get('User-Agent') || 'unknown';
  const country = request.headers.get('CF-IPCountry') || 'unknown';

  // Generate the disclosure document
  const disclosureHTML = generateDisclosureHTML({
    submission_id: submissionId,
    inventor_name: inventor_name || '',
    inventor_email: inventor_email || '',
    title,
    disclosure_text,
  });

  // Store in D1
  try {
    await env.DB.prepare(
      `INSERT INTO ipatent_submissions (submission_id, inventor_name, inventor_email, title, disclosure_text, status, ip_address, user_agent)
       VALUES (?, ?, ?, ?, ?, 'generated', ?, ?)`
    ).bind(submissionId, inventor_name || '', inventor_email || '', title, disclosure_text, ip, ua).run();

    // Analytics event
    await env.DB.prepare(
      `INSERT INTO ipatent_analytics (event_type, page_url, ip_address, user_agent, country, metadata)
       VALUES ('submission', '/api/submit', ?, ?, ?, ?)`
    ).bind(ip, ua, country, JSON.stringify({ submission_id: submissionId, title })).run();
  } catch (dbErr) {
    console.error('DB write failed:', dbErr);
    // Still return the disclosure even if DB fails
  }

  return new Response(disclosureHTML, {
    status: 201,
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      ...CORS_HEADERS,
      'X-Submission-ID': submissionId,
    },
  });
}

async function handleAnalytics(request, env) {
  if (request.method === 'OPTIONS') return cors(new Response(null, { status: 204 }));

  let body = {};
  if (request.method === 'POST') {
    try { body = await request.json(); } catch { /* OK */ }
  }

  const eventType = body.event_type || 'pageview';
  const pageUrl = body.page_url || request.headers.get('Referer') || '/';
  const referrer = body.referrer || request.headers.get('Referer') || '';
  const ip = request.headers.get('CF-Connecting-IP') || 'unknown';
  const ua = request.headers.get('User-Agent') || 'unknown';
  const country = request.headers.get('CF-IPCountry') || 'unknown';
  const sessionId = body.session_id || crypto.randomUUID();
  const metadata = body.metadata ? JSON.stringify(body.metadata) : '{}';

  try {
    await env.DB.prepare(
      `INSERT INTO ipatent_analytics (event_type, page_url, referrer, ip_address, user_agent, country, session_id, metadata)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?)`
    ).bind(eventType, pageUrl, referrer, ip, ua, country, sessionId, metadata).run();
  } catch (dbErr) {
    console.error('Analytics write failed:', dbErr);
  }

  return json({ success: true, session_id: sessionId }, 200);
}

async function handleStats(request, env) {
  try {
    const [totalSubmissions, totalEvents, recentSubmissions] = await Promise.all([
      env.DB.prepare('SELECT COUNT(*) as count FROM ipatent_submissions').first(),
      env.DB.prepare('SELECT COUNT(*) as count FROM ipatent_analytics').first(),
      env.DB.prepare(
        'SELECT submission_id, title, inventor_name, status, created_at FROM ipatent_submissions ORDER BY created_at DESC LIMIT 20'
      ).all(),
    ]);

    const byCountry = await env.DB.prepare(
      'SELECT country, COUNT(*) as count FROM ipatent_analytics WHERE country IS NOT NULL GROUP BY country ORDER BY count DESC LIMIT 20'
    ).all();

    const byEvent = await env.DB.prepare(
      'SELECT event_type, COUNT(*) as count FROM ipatent_analytics GROUP BY event_type ORDER BY count DESC'
    ).all();

    return json({
      submissions: { total: totalSubmissions?.count || 0, recent: recentSubmissions?.results || [] },
      analytics: { total: totalEvents?.count || 0, by_country: byCountry?.results || [], by_event: byEvent?.results || [] },
    });
  } catch (err) {
    return json({ error: 'Stats unavailable', detail: err.message }, 500);
  }
}

async function handleHealth() {
  return json({ status: 'ok', service: 'ipatent-api', version: '1.0.0', timestamp: new Date().toISOString() });
}

// ── Router ──

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const path = url.pathname;

    // CORS preflight
    if (request.method === 'OPTIONS') {
      return cors(new Response(null, { status: 204 }));
    }

    try {
      if (path === '/api/submit') return handleSubmit(request, env);
      if (path === '/api/analytics') return handleAnalytics(request, env);
      if (path === '/api/stats') return handleStats(request, env);
      if (path === '/api/health') return handleHealth();

      // Catch-all: redirect to main site
      return Response.redirect('https://ipatent.me', 302);
    } catch (err) {
      console.error('Unhandled error:', err);
      return json({ error: 'Internal server error', detail: err.message }, 500);
    }
  },
};
